#!/bin/bash

#!/bin/bash
#SBATCH --job-name=MICROMP
#SBATCH --workdir=.
#SBATCH --output=omp.out
#SBATCH --error=omp.err
#SBATCH --cpus-per-task=1
#SBATCH --ntasks=1
#SBATCH --exclusive
#SBATCH --time=01:00:00
##SBATCH --qos=bsc_case
#SBATCH --qos=debug

N=30
NGP=100

folder="res_${N}_${NGP}"
mkdir -p ${folder}

procs=(1 2 4 8 16 32 48)

for i in ${procs[@]}; do

echo "Executing with $i Threads"
export OMP_NUM_THREADS=${i}
time ../build/test/test_omp $N $NGP > ${folder}/res_${i}.dat

done
