#!/bin/bash

#SBATCH --job-name=MICROMP
#SBATCH --workdir=.
#SBATCH --output=omp_%j.out
#SBATCH --error=omp_%j.err
#SBATCH --cpus-per-task=1
#SBATCH --ntasks=1
#SBATCH --exclusive
#SBATCH --time=01:00:00
##SBATCH --qos=bsc_case
#SBATCH --qos=debug

. vars.sh

procs=(1 2 4 8 16 32 48)

for i in ${procs[@]}; do
	for N in ${sizes[@]}; do

		folder="res_${N}_${NGP}"
		mkdir -p ${folder}

		echo "Executing with $i Threads"
		export OMP_NUM_THREADS=${i}
		time ../build/test/test_omp $N $NGP > ${folder}/res_${i}.dat

	done
done
